### ISSUE TITLE
SyzyASAN canaries report most crashes through Kasko

### ISSUE THREAD

**Issue by sigurasg** [google/syzygy#18]
Since SyzyASAN is the last registered UEF, it ends up handling most crashes, but not all. Some crashes are still delegated directly to the BP handler, such as e.g. inside a WrappedWindowProc. It turns out SyzyASAN delegates to Chrome->Kasko always, which is kind of weird, and doesn't improve reliability. There are also cases where this falls over for reasons unknown, and SyzyASAN/Kasko end up crashing and reporting through BreakPad.

**Comment by chhamilton** [comment]
This has been addressed here:

https://github.com/google/syzygy/commit/4578f181d22621226285e29fa1f823b05ff13f3c

Specifically at this line:

https://github.com/google/syzygy/commit/4578f181d22621226285e29fa1f823b05ff13f3c#diff-9d2495817d24a8040db267992ca47f0bR1188
