### ISSUE TITLE
Error handling code should not be optimized

### ISSUE THREAD

**Issue by chhamilton** [google/syzygy#22]
This will allow us full fidelity when debugging things that have gone wrong during the error handling code path of the RTL. In some cases using base::Alias might be sufficient to ensure visibility of important data.

**Comment by sigurasg** [comment]
Since we don't get module globals, it would be nice to simply copy salient data to stack. Notably the breakpad handler struct, which has a bunch of function pointers we acquire with GetProcAddress.

**Comment by chhamilton** [comment]
Might also be nice to use Kasko to grab IAT tables, etc.
