### ISSUE TITLE
Update instrumentation instructions for gn

### ISSUE THREAD

**Issue by mikelawther** [google/syzygy#49]
The instructions at https://github.com/google/syzygy/wiki/SyzyASanHowTo refer to gyp, but we use gn on Chrome now.

My best guess is that I should use

    gn gen --args="is_syzyasan=true is_component_build=false is_debug=false symbol_level=2" out\syzygy

**Comment by mikelawther** [comment]
I finally successfully built with:

  gn gen --args="is_syzyasan=true is_component_build=false is_debug=false symbol_level=2 target_cpu=\"x86\"" out\syzygy
  ninja -C out\syzygy All_syzygy

**Comment by sebmarchand** [comment]
Thanks ! I've fixed this.
